- name: add postgres repositories
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main
    state: present

- name: adding repository key
  apt_key:
    url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
    state: present

- name: updating apt cache
  apt:
    update_cache: yes

- name: Install database packages
  apt: name={{item}} state=present
  with_items:
    - python-psycopg2
    - libpq-dev
    - postgresql-client-9.6
    - postgresql-9.6
    - postgresql-contrib-9.6
    - postgresql-plpython3-9.6
    - postgresql-9.6-pllua
    - luajit
    - postgresql-9.6-pgtap
    - pgtap

- name: create database user
  become: true
  become_user: postgres
  postgresql_user:
    name: "{{ user }}"
    role_attr_flags: SUPERUSER

- name: create database with name as user
  become: true
  become_user: postgres
  postgresql_db:
    name: "{{ user }}"
